name: Build and Upload Android APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Run pub get
        run: flutter pub get

      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      - name: Build APK via Gradle
        env:
          GRADLE_OPTS: "-Xmx3072m -XX:MaxMetaspaceSize=512m"
        run: |
          cd android
          ./gradlew assembleRelease -Pandroid.newDsl=false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
